language: python
python:
  - "3.7"

stages:
    - name: lint

jobs:
  include:
    - stage: lint
      name: Lint code base
      install:
        - pip install poetry
        - poetry install
        - poetry add pylint isort flake8 black
      script:
        - poetry run pytest .
        - export modifiedFiles=$(git diff --name-only HEAD~1 | grep -i ^.*\.py$)
        - echo $modifiedFiles
        - poetry run pylint $modifiedFiles
        - poetry run flake8 $modifiedFiles
        - poetry run black --check $modifiedFiles
        - poetry run isort --check $modifiedFiles
