language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install poetry
  - poetry add pylint
  - poetry install
# command to run tests
script:
#  - poetry run pytest
  - git diff --name-only HEAD~1 | grep -i .*\.py | xargs poetry run pylint

