language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  - poetry add pylint isort flake8 black
# command to run tests
script:
  - ls -l
  - export modifiedFiles=$(git diff --name-only HEAD~1 | grep -i ^.*\.py$)
  - poetry run pylint modifiedFiles
  - poetry run flake8 modifiedFiles
  - poetry run black --check modifiedFiles
  - poetry run isort --check modifiedFiles

