language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install poetry
  - poetry install
  - poetry add pylint
# command to run tests
script:
  - ls -l
  - poetry run pylint ./app.py
#  - poetry run pytest
#  - git diff --name-only HEAD~1 | grep -i .*\.py | xargs poetry run pylint

