language: python
python:
  - "3.7"

branches:
  only:
    - master

install:
  - pip install poetry
  - poetry install
  - poetry add pylint isort flake8 black

script:
  - poetry run pytest .
  - export modifiedFiles=$(git diff --name-only HEAD~1 | grep -i ^.*\.py$)
  - echo $modifiedFiles
  - if [ $modifiedFiles ]; then poetry run pylint $modifiedFiles; fi;
  - if [ $modifiedFiles ]; then poetry run flake8 $modifiedFiles; fi;
  - if [ $modifiedFiles ]; then poetry run black --check $modifiedFiles; fi;
  - if [ $modifiedFiles ]; then poetry run isort --check $modifiedFiles; fi;
