name: deploy-master-on-vps
on:
  push:
    branches:
      - master
jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 51.210.9.60
          REMOTE_USER: ubuntu
          REMOTE_PORT: 2288
          TARGET: /home/ubuntu/actions
          EXCLUDE: ".git/, .venv/"

      - name: ssh command
        run: ssh -i ~/.ssh/deploy_key ubuntu@51.210.9.60 -p 2288 "bash /home/ubuntu/deploy.sh"