name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          REMOTE_HOST: 51.210.9.60
          REMOTE_USER: ubuntu
          REMOTE_PORT: 2288
          TARGET: /home/ubuntu/