name: learn-github-actions
on: [push]
jobs:
  deploy-on-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

#      - name: Load cached venv
#        id: cached-poetry-dependencies
#        uses: actions/cache@v2
#        with:
#          path: .venv
#          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

#      - name: Install library
#        run: poetry install --no-interaction

#      - name: Lint Code Base
#        uses: github/super-linter@v4
#        env:
#          VALIDATE_ALL_CODEBASE: false
#          DEFAULT_BRANCH: master
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
          coverage report

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 51.210.9.60
          REMOTE_USER: ubuntu
          REMOTE_PORT: 2288
          TARGET: /home/ubuntu/actions
          EXCLUDE: .git/

#      - name: ssh command
#        run: |
#          ssh -i ~/.ssh/deploy_key ubuntu@51.210.9.60 -p 2288 "touch /home/ubuntu/touched"